### PR TITLE
Use templates from our design-system for card layouts

### PR DESCRIPTION
**Pull request by zacoppotamus**
Merge this before merging our new build-system to `develop`. 

This uses templates from our `design-system` to generate appropriate card layouts (two supported at the moment: `basic` and `us_protests`).

### CODE REVIEW

**Comment by ebefarooqui** [comment]
Attempting to run this locally, but its missing all of the `config/...` files that are required. Are those checked in? I think it'd be best to merge this one first and then test the whole system build & card changes in the merged branch.

More particularly error-wise, seeing that the module for `.../config/webpack.config` is missing when I run the `CONFIG=... npm run react-scripts:start` command

**Review by ebefarooqui — APPROVED** [review]

**Comment by breezykermo** [comment]
Yep, I agree with Ebe- let’s merge this so it’s just one PR to consider

**Comment by zacoppotamus** [comment]
Done. Opening up the other PR for review.

**Comment by zacoppotamus** [comment]
@ebefarooqui You're right, the `.gitignore` matches `*.config.js`. I will fix this in the `feature/build-system-cra-ejected` branch.

**Pull request merged**
