### PR TITLE
Topic/basic smoke test

### PR DESCRIPTION
**Pull request by scztt**
A simple example of unit testing on travis - this should at least minimally validate that the server is launchable and can return some data. Usage of mocha is pretty minimal here, so this could easily be swapped for another framework if needed. This may or may not be the way ya'll would like to go re testing, but I think it's important to have at least SOME minimal green/red information on travis builds - this is a start.

### CODE REVIEW

**Comment by scztt** [comment]
Hold off on merging this - travis has an issue with 
`subprocess.kill` that seems to be causing the test phase to time out. Looking in to alternative ways of managing the subprocess.

**Comment by scztt** [comment]
Travis failures are resolved - this is now green.

**Comment by breezykermo** [comment]
Thanks for this -- agreed, and looks good. My only request before merge would be to change the test runner to [Ava](https://github.com/avajs/ava), to keep the framework consistent between this repo and [datasheet-server](https://github.com/forensic-architecture/datasheet-server/).

**Comment by scztt** [comment]
Yup, I noticed that - I started switching over to ava - one more problem to solve and then I'll add that.

**Pull request merged**
