### PR TITLE
Getting rid of duplicate association logic, removing check and error …

### PR DESCRIPTION
**Pull request by ebefarooqui**
Removes check for duplicate associations. Subsequently removes error generation as well

### CODE REVIEW

**Comment by breezykermo** [comment]
Sorry, I think the issue I created in tasks was unclear. I don't think we should remove this check and associated error message-- we should just modify the example sheet so that it doesn't have duplicate associations by default, so that the error doesn't show up when a new user first starts up a timemap instance.

**Review by breezykermo — CHANGES_REQUESTED** [review]
See above.

**Comment by ebefarooqui** [comment]
Nixing this as it's not relevant

**Comment by ebefarooqui** [comment]
Nixing this as per above

**Pull request closed without merging**
