### PR TITLE
Topic/port gaearon commits

### PR DESCRIPTION
**Pull request by breezykermo**
Porting @gaearon commits from the following PRs to https://github.com/bellingcat/ukraine-timemap:
- [Fix some React warnings](https://github.com/bellingcat/ukraine-timemap/pull/18)
- [Fix warning about Tab and TabPanel](https://github.com/bellingcat/ukraine-timemap/pull/19)
- [Update to React 18](https://github.com/bellingcat/ukraine-timemap/pull/20) 
- [Improve dragging performance](https://github.com/bellingcat/ukraine-timemap/pull/22)
- [Don't use hashes for keys](https://github.com/bellingcat/ukraine-timemap/pull/24) 

See discussion in original PRs for more context.

### CODE REVIEW

**Comment by gaearon** [comment]
https://github.com/bellingcat/ukraine-timemap/pull/24 is a bit risky so it would be good to get confirmation on the questions there.

**Comment by breezykermo** [comment]
Thanks Dan, responding inline there now.

**Comment by breezykermo** [comment]
I'll remove those commits from this PR for now.

**Comment by gaearon** [comment]
Let's wait for https://github.com/bellingcat/ukraine-timemap/pull/29 too.

**Comment by breezykermo** [comment]
Merging this now with flashing fixed.

**Pull request merged**
